services:
  - type: web
    name: car-price-prediction
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn application:app"
    plan: free
    pythonVersion: 3.10.0
